Nomos/Models/Legislacao/LegislacaoEditViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Nomos.Models.Legislacao
{

    public class LegislacaoEditViewModel
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public int CategoriaId { get; set; }
        public int TipoId { get; set; }
        public DateTime DataPublicacao { get; set; }                
        public DateTime? DataInicioVigencia { get; set; }
        public int SituacaoId { get; set; }
        public int OrgaoId { get; set; }
        public string Observacao { get; set; }
        public string Link { get; set; }

        public SelectList Categorias { get; set; }
        public SelectList Tipos { get; set; }
        public SelectList Orgaos { get; set; }
        public SelectList Situacoes { get; set; }

        public RelacionadosViewModel Relacionados { get; set; }
    }

}

Nomos/Models/Legislacao/LegislacaoFilterViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nomos.Models.Legislacao
{
    public class LegislacaoFilterViewModel
    {
        public string Codigo { get; set; }
        public string Titulo { get; set; }
        public int CategoriaId { get; set; }
        public DateTime? DataPublicacao { get; set; }
        public int SituacaoId { get; set; }
        public int OrgaoId { get; set; }


        public SelectList Categorias { get; set; }
        public SelectList Orgaos { get; set; }
        public SelectList Situacoes { get; set; }

    }
}

Nomos/Models/Legislacao/LegislacaoIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nomos.Models.Legislacao
{
    public class LegislacaoIndexViewModel
    {

        public LegislacaoIndexViewModel()
        {
            ListaViewModel = new List<LegislacaoListViewModel>();
            FilterViewModel = new LegislacaoFilterViewModel();
        }

        public IList<LegislacaoListViewModel> ListaViewModel { get; set; }

        public LegislacaoFilterViewModel FilterViewModel { get; set; }

    }
}

Nomos/Models/Legislacao/LegislacaoListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nomos.Models.Legislacao
{
    public class LegislacaoListViewModel
    {
        public long Id { get; set; }
        public string Codigo { get; set; }
        public string Titulo { get; set; }
        public string DataPublicacao { get; set; }
        public string Situacao { get; set; }
        public string Orgao { get; set; }        
        public string Link { get; set; }
    }
}

Nomos/Models/Legislacao/LegislacaoNewViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Nomos.Models.Legislacao
{
    public class LegislacaoNewViewModel
    {
        public string Codigo { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public int CategoriaId { get; set; }
        public int TipoId { get; set; }
        public DateTime DataPublicacao { get; set; }
        public DateTime? DataInicioVigencia { get; set; }
        public int SituacaoId { get; set; }
        public int OrgaoId { get; set; }
        public string Observacao { get; set; }
        public string Link { get; set; }

        public SelectList Categorias { get; set; }
        public SelectList Orgaos { get; set; }
        public SelectList Situacoes { get; set; }
        public SelectList Tipos { get; set; }


    }
}

Nomos/Models/Legislacao/RelacionadosViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nomos.Models.Legislacao
{
    public class RelacionadosViewModel
    {
        public List<LegislacaoListViewModel> LegislacaoDisponivel { get; set; }
        public List<LegislacaoListViewModel> LegislacaoRelacionada { get; set; }
    }
}

Nomos/Controllers/LegislacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Nomos.Business.CategoriaLegislacao;
using Nomos.Business.Legislacao;
using Nomos.Business.Orgao;
using Nomos.Business.SituacaoLegislacao;
using Nomos.Entities;
using Nomos.Models;
using Nomos.Models.Legislacao;

namespace Nomos.Controllers
{

    [Authorize]
    public class LegislacaoController : BaseController
    {
        ICategoriaLegislacaoBusiness _categoriaLegislacaoBusiness;
        ITipoLegislacaoBusiness _tipoLegislacaoBusiness;
        IOrgaoBusiness _orgaoBusiness;
        ISituacaoLegislacaoBusiness _situacaoLegislacaoBusiness;
        ILegislacaoBusiness _legislacaoBusiness;
        private readonly IMapper _mapper;

        public LegislacaoController(
            ICategoriaLegislacaoBusiness categoriaLegislacaoBusiness,
            IOrgaoBusiness orgaoBusiness,
            ISituacaoLegislacaoBusiness situacaoLegislacaoBusiness,
            ILegislacaoBusiness legislacaoBusiness,
            ITipoLegislacaoBusiness tipoLegislacaoBusiness,
            IMapper mapper,
            ICompositeViewEngine viewEngine) : base(viewEngine)
        {
            _categoriaLegislacaoBusiness = categoriaLegislacaoBusiness;
            _tipoLegislacaoBusiness = tipoLegislacaoBusiness;
            _orgaoBusiness = orgaoBusiness;
            _situacaoLegislacaoBusiness = situacaoLegislacaoBusiness;
            _legislacaoBusiness = legislacaoBusiness;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var lista = _legislacaoBusiness.Listar(20);
            var listaModel = _mapper.Map<IList<LegislacaoListViewModel>>(lista);

            var model = new LegislacaoIndexViewModel();
            model.ListaViewModel = listaModel;
            model.FilterViewModel.Categorias = RetornarCategorias();
            model.FilterViewModel.Orgaos = RetornarOrgaos();
            model.FilterViewModel.Situacoes = RetornarSituacoes();

            return View(model);
        }

        public IActionResult Edit(int id)
        {
            
            var legislacao = _legislacaoBusiness.Buscar(id);
            var model = _mapper.Map<LegislacaoEditViewModel>(legislacao);
            model.Categorias = RetornarCategorias();
            model.Orgaos = RetornarOrgaos();
            model.Situacoes = this.RetornarSituacoes();
            model.Tipos = this.RetornarTiposLegislacao();
            model.Relacionados = this.RetornarRelacionados(legislacao.LegislacaoImpactada);

            return View(model);
        }

        private RelacionadosViewModel RetornarRelacionados(ICollection<LegislacaoImpactada> legislacaoImpactadas)
        {
            var retorno = new RelacionadosViewModel();
            retorno.LegislacaoDisponivel = new List<LegislacaoListViewModel>();
            retorno.LegislacaoRelacionada = new List<LegislacaoListViewModel>();


            var todasLegislacoes = _legislacaoBusiness.Listar(0);
                        


            foreach(var l in legislacaoImpactadas)
            {
                retorno.LegislacaoRelacionada.Add(new LegislacaoListViewModel
                {
                    Id = l.LegislacaoRelacionadaId,
                    Titulo = l.LegislacaoRelacionada.Titulo,
                    Codigo = l.LegislacaoRelacionada.Codigo
                });
            }

            foreach (var legislacao in todasLegislacoes)
            {
                if(!legislacaoImpactadas.Any(li => li.LegislacaoRelacionadaId == legislacao.Id))
                {
                    retorno.LegislacaoDisponivel.Add(new LegislacaoListViewModel
                    {
                        Id = legislacao.Id,
                        Titulo = legislacao.Titulo,
                        Codigo = legislacao.Codigo
                    });
                }
            }


            return retorno;
        }

        public IActionResult New()
        {
            var model = new LegislacaoNewViewModel();
            model.Categorias = this.RetornarCategorias();
            model.Orgaos = this.RetornarOrgaos();
            model.Situacoes = this.RetornarSituacoes();
            model.Tipos = this.RetornarTiposLegislacao();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Filtrar([FromBody]LegislacaoFilterViewModel model)
        {

            var filtro = _mapper.Map<Entities.Legislacao>(model);

            var lista = _legislacaoBusiness.Filtrar(filtro);
            var listaModel = _mapper.Map<IList<LegislacaoListViewModel>>(lista);

            var htmlRetorno = await RenderPartialViewToString("List", listaModel);
            
            return Json(htmlRetorno);
        }

        [HttpPost]
        public IActionResult Incluir([FromBody]LegislacaoNewViewModel model)
        {
            Entities.Legislacao entidade = null;

            try
            {
                if (_legislacaoBusiness.VerificarExisteCodigo(model.Codigo))
                    return Json(new { Sucesso = false, Mensagem = "Código já existente" });
                else
                {
                    entidade = _mapper.Map<Entities.Legislacao>(model);
                    _legislacaoBusiness.Incluir(entidade);
                }
            }
            catch (Exception ex)
            {
                return BadRequest(new { Mensagem = ex.Message });
            }

            return Json(new { Sucesso = true, entidade.Id });
        }


        [HttpPost]
        public IActionResult Atualizar([FromBody]LegislacaoEditViewModel model)
        {
            try
            {
                var entidade = _mapper.Map<Entities.Legislacao>(model);
                _legislacaoBusiness.Atualizar(entidade);

                var legislacoesImpactadas = new List<LegislacaoImpactada>();


                foreach (var item in model.Relacionados.LegislacaoRelacionada)
                {
                    legislacoesImpactadas.Add(new LegislacaoImpactada
                    {
                        LegislacaoPrincipalId = model.Id,
                        LegislacaoRelacionadaId = item.Id
                    });
                }

                _legislacaoBusiness.AtualizarImpactadas(legislacoesImpactadas);


            }
            catch (Exception ex)
            {
                return BadRequest(new { Mensagem = ex.Message });
            }

            return Json(new { Sucesso = true });
        }

        [HttpPost]
        public IActionResult Excluir([FromBody]LegislacaoEditViewModel model)
        {

            try
            {
                _legislacaoBusiness.Excluir(model.Id);
            }
            catch (Exception ex)
            {
                return BadRequest(new { Mensagem = ex.Message });
            }

            return Json(new { Sucesso = true });
        }

        private SelectList RetornarCategorias()
        {

            var categorias = _categoriaLegislacaoBusiness.Listar();

            List<ItemDropModel> itens = new List<ItemDropModel>();

            itens.Add(new ItemDropModel { Id = 0, Nome = "--Selecione--" });

            foreach (var categoria in categorias)
            {
                itens.Add(new ItemDropModel { Id = categoria.Id, Nome = categoria.Nome });
            }

            return new SelectList(itens, "Id", "Nome");
        }

        private SelectList RetornarTiposLegislacao()
        {

            var tiposLegislacao = _tipoLegislacaoBusiness.Listar();

            List<ItemDropModel> itens = new List<ItemDropModel>();

            itens.Add(new ItemDropModel { Id = 0, Nome = "--Selecione--" });

            foreach (var tipo in tiposLegislacao)
            {
                itens.Add(new ItemDropModel { Id = tipo.Id, Nome = tipo.Nome });
            }

            return new SelectList(itens, "Id", "Nome");
        }

        private SelectList RetornarOrgaos()
        {

            var orgaos = _orgaoBusiness.Listar();

            List<ItemDropModel> itens = new List<ItemDropModel>();

            itens.Add(new ItemDropModel { Id = 0, Nome = "--Selecione--" });

            foreach (var orgao in orgaos)
            {
                itens.Add(new ItemDropModel { Id = orgao.Id, Nome = orgao.Nome });
            }

            return new SelectList(itens, "Id", "Nome");
        }

        private SelectList RetornarSituacoes()
        {
            var situacoes = _situacaoLegislacaoBusiness.Listar();

            List<ItemDropModel> itens = new List<ItemDropModel>();

            itens.Add(new ItemDropModel { Id = 0, Nome = "--Selecione--" });

            foreach (var situacao in situacoes)
            {
                itens.Add(new ItemDropModel { Id = situacao.Id, Nome = situacao.Nome });
            }

            return new SelectList(itens, "Id", "Nome");
        }

    }
}

Nomos/Views/Legislacao/Edit.cshtml
@model Nomos.Models.Legislacao.LegislacaoEditViewModel

@{
    ViewData["Title"] = "Legislação - Edição";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section styles{
    <link rel="Stylesheet" href="@Href("~/css/Legislacao/Edit.css")" />
    <link rel="Stylesheet" href="@Href("~/css/Legislacao/Relacionados.css")" />
}

<h3>Legislação</h3>
<hr />
<div class="form-group">
    <div class="row">
        <div class="col-sm-12">
            <button id="btn-salvar" onclick="salvarClick()" type="button" class="btn btn-primary" aria-label="Left Align">Salvar <span class="fa fa-save fa-lg" aria-hidden="true"></span></button>
            <button id="btn-cancelar" onclick="cancelarClick()" type="button" class="btn btn-warning" aria-label="Left Align">Cancelar <span class="fa fa-times fa-lg" aria-hidden="true"></span></button>
            <button id="btn-excluir" onclick="excluirClick()" type="button" class="btn btn-danger" aria-label="Left Align">Excluir <span class="fa fa-trash fa-lg" aria-hidden="true"></span></button>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="form-group">

            <div class="row">
                <input id="id" type="hidden" value="@Model.Id" />
                <div class="col-sm-2">
                    <label>Código</label>
                    <input id="codigo" class="form-control" type="text" maxlength="50" value="@Model.Codigo" />
                </div>
                <div class="col-sm-6">
                    <label>Título</label>
                    <input id="titulo" class="form-control" type="text" maxlength="100" value="@Model.Titulo" />
                </div>
                <div class="col-sm-4">
                    <label>Tipo</label>
                    @Html.DropDownListFor(model => model.TipoId, Model.Tipos, new { @id = "tipo", @class = "form-control input-sm", @style = "width:100%;" })
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <label>Descrição</label>
                    <input id="descricao" class="form-control" type="text" maxlength="500" value="@Model.Descricao" />
                </div>
            </div>


            <div class="row">

                <div class="col-sm-2">
                    <label>Categoria</label>
                    @Html.DropDownListFor(model => model.CategoriaId, Model.Categorias, new { @id = "categoria", @class = "form-control input-sm", @style = "width:100%;" })
                </div>

                <div class="col-sm-2">
                    <label>Data Publicação</label>
                    <input id="dataPublicacao" class="form-control" type="text" value="@Model.DataPublicacao" />
                </div>

                <div class="col-sm-2">
                    <label>Data Início Vigência</label>
                    <input id="dataInicioVigencia" class="form-control" type="text" value="@Model.DataInicioVigencia" />
                </div>

                <div class="col-sm-4">
                    <label>Orgão</label>
                    @Html.DropDownListFor(model => model.OrgaoId, Model.Orgaos, new { @id = "orgao", @class = "form-control input-sm", @style = "width:100%;" })
                </div>


                <div class="col-sm-2">
                    <label>Situação</label>
                    @Html.DropDownListFor(model => model.SituacaoId, Model.Situacoes, new { @id = "situacao", @class = "form-control input-sm", @style = "width:100%;" })
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <label>Link</label>
                    <form class="form-link-input">
                        <input id="link" class="form-control link-input" type="text" maxlength="4000" value="@Model.Link" />
                        <a class="link-input-button" id="linkAcesso"><i class="fa fa-globe" onclick="abrirUrl()"></i></a>
                    </form>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <label>Observação</label>
                    <textarea id="observacao" class="form-control" rows="10" maxlength="8000">@Model.Observacao</textarea>
                </div>
            </div>
        </div>

    </div>
</div>
@Html.Partial("~//Views/Legislacao/Relacionados.cshtml", Model.Relacionados)
<hr />
<div class="form-group">
    <div class="row">
        <div class="col-sm-12">
            <button id="btn-salvar" onclick="salvarClick()" type="button" class="btn btn-primary" aria-label="Left Align">Salvar <span class="fa fa-save fa-lg" aria-hidden="true"></span></button>
            <button id="btn-cancelar" onclick="cancelarClick()" type="button" class="btn btn-warning" aria-label="Left Align">Cancelar <span class="fa fa-times fa-lg" aria-hidden="true"></span></button>
            <button id="btn-excluir" onclick="excluirClick()" type="button" class="btn btn-danger" aria-label="Left Align">Excluir <span class="fa fa-trash fa-lg" aria-hidden="true"></span></button>
        </div>
    </div>
</div>
<script src="~/js/Legislacao/Edit.js"></script>

<script>
    var urlAtualizar = encodeURI('@Url.Action("Atualizar", "Legislacao")');
    var urlExcluir = encodeURI('@Url.Action("Excluir", "Legislacao")');
</script>

Nomos/Views/Legislacao/Filter.cshtml
@model Nomos.Models.Legislacao.LegislacaoFilterViewModel

<div class="card">
    <div class="card-body">
        <div class="form-group">

            <div class="row">
                <div class="col-sm-4">
                    <label>Código</label>
                    <input id="codigo" class="form-control" type="text" maxlength="50" />
                </div>

                <div class="col-sm-4">
                    <label>Título</label>
                    <input id="titulo" class="form-control" type="text" maxlength="50" />
                </div>

                <div class="col-sm-4">
                    <label>Categoria</label>
                    @Html.DropDownListFor(model => model.Categorias, Model.Categorias, new { @id = "categoria", @class = "form-control input-sm", @style = "width:100%;" })
                </div>
            </div>

            <div class="row mt-2">

                <div class="col-sm-4">
                    <label>Data Publicação</label>
                    <input id="dataPublicacao" class="form-control" type="text" maxlength="50" />
                </div>

                <div class="col-sm-4">
                    <label>Orgão</label>
                    @Html.DropDownListFor(model => model.Orgaos, Model.Orgaos, new { @id = "orgao", @class = "form-control input-sm", @style = "width:100%;" })
                </div>

                <div class="col-sm-2">
                    <label>Situação</label>
                    @Html.DropDownListFor(model => model.Situacoes, Model.Situacoes, new { @id = "situacao", @class = "form-control input-sm", @style = "width:100%;" })
                </div>

                <div class="col-sm-2 text-right">
                    <br>
                    <button id="btn-filtrar" onclick="filtrarClick()" type="button" class="btn btn-primary" aria-label="Left Align">Filtrar <span class="fa fa-search fa-lg" aria-hidden="true"></span></button>
                </div>
            </div>
        </div>
    </div>
</div>
<hr />

<script src="~/js/Legislacao/Filter.js"></script>


<script>
    var urlFiltrar = encodeURI('@Url.Action("Filtrar", "Legislacao")');
</script>

Nomos/Views/Legislacao/Index.cshtml
@model Nomos.Models.Legislacao.LegislacaoIndexViewModel

@{
    ViewData["Title"] = "Legislação";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section styles{
    @*<link rel="Stylesheet" href="@Href("~/css/Legislacao/Index.css")" />*@
}

<div class="form-group">
    <div class="row">
        <div class="col-sm-2">
            <h3>Legislação</h3>
        </div>
        <div class="col-sm-10 text-right">
            <button id="btn-incluir" onclick="incluirClick()" type="button" class="btn btn-success" aria-label="Left Align"><span class="fa fa-file fa-lg" aria-hidden="true"></span></button>
        </div>
    </div>
</div>
<hr />

@Html.Partial("~//Views/Legislacao/Filter.cshtml", Model.FilterViewModel)
<div id="resultado">
    @Html.Partial("~//Views/Legislacao/List.cshtml", Model.ListaViewModel)
</div>

<script src="~/js/Legislacao/Index.js"></script>

Nomos/Views/Legislacao/List.cshtml
@model List<Nomos.Models.Legislacao.LegislacaoListViewModel>


<div class="box">
    <div class="box-content">
        @if (Model.Count > 0)
        {
            <table id="gridLegislacao" class="table table-bordered table-striped">

                <thead>
                    <tr>
                        <th hidden>Id</th>
                        <th>Código</th>
                        <th>Título</th>
                        <th>Data Publicação</th>
                        <th>Situação</th>
                        <th>Orgão</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                <thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr id="rowId_@item.Id">
                            <td hidden>@item.Id"</td>
                            <td>@item.Codigo</td>
                            <td>@item.Titulo</td>
                            <td>@item.DataPublicacao</td>
                            <td>@item.Situacao</td>
                            <td>@item.Orgao</td>
                            <td style="text-align:center"><i class="fa fa-fw fa-edit" style="cursor:pointer" onclick="editarClick(@item.Id)"></i></td>
                            <td style="text-align:center"><i class="fa fa-fw fa-globe" style="cursor:pointer" onclick="abrirUrlClick('@item.Link')"></i></td>
                            <td style="text-align:center"><i class="fa fa-fw fa-trash" style="cursor:pointer" onclick="excluirClick(@item.Id)"></i></td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <table>
                <thead>
                    <tr>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="color:red">Nenhum registro encontrado</td>
                    </tr>
                </tbody>
            </table>
        }

    </div>
    <!--end: BOX CONTENT-->
</div>
<!--end: BOX-->

<script src="~/js/Legislacao/List.js"></script>


<script>
    var urlExcluir = encodeURI('@Url.Action("Excluir", "Legislacao")');
</script>

Nomos/Views/Legislacao/New.cshtml
@model Nomos.Models.Legislacao.LegislacaoNewViewModel

@{
    ViewData["Title"] = "Legislação - Inclusão";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section styles{
    <link rel="Stylesheet" href="@Href("~/css/Legislacao/New.css")" />
}

<h3>Legislação</h3>
<hr />
<div class="form-group">
    <div class="row">
        <div class="col-sm-12">
            <button id="btn-salvar" onclick="salvarclick()" type="button" class="btn btn-primary" aria-label="Left Align">Salvar <span class="fa fa-save fa-lg" aria-hidden="true"></span></button>
            <button id="btn-cancelar" onclick="cancelarclick()" type="button" class="btn btn-warning" aria-label="Left Align">Cancelar <span class="fa fa-times fa-lg" aria-hidden="true"></span></button>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="form-group">

            <div class="row">
                <div class="col-sm-2">
                    <label>Código</label>
                    <input id="codigo" class="form-control" type="text" maxlength="50" />
                </div>
                <div class="col-sm-6">
                    <label>Título</label>
                    <input id="titulo" class="form-control" type="text" maxlength="100" />
                </div>
                <div class="col-sm-4">
                    <label>Tipo</label>
                    @Html.DropDownListFor(model => model.Tipos, Model.Tipos, new { @id = "tipo", @class = "form-control input-sm", @style = "width:100%;" })
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <label>Descrição</label>
                    <input id="descricao" class="form-control" type="text" maxlength="500" />
                </div>
            </div>


            <div class="row">

                <div class="col-sm-2">
                    <label>Categoria</label>
                    @Html.DropDownListFor(model => model.Categorias, Model.Categorias, new { @id = "categoria", @class = "form-control input-sm", @style = "width:100%;" })
                </div>

                <div class="col-sm-2">
                    <label>Data Publicação</label>
                    <input id="dataPublicacao" class="form-control" type="text" />
                </div>

                <div class="col-sm-2">
                    <label>Data Início Vigência</label>
                    <input id="dataInicioVigencia" class="form-control" type="text" />
                </div>

                <div class="col-sm-4">
                    <label>Orgão</label>
                    @Html.DropDownListFor(model => model.Orgaos, Model.Orgaos, new { @id = "orgao", @class = "form-control input-sm", @style = "width:100%;" })
                </div>


                <div class="col-sm-2">
                    <label>Situação</label>
                    @Html.DropDownListFor(model => model.Situacoes, Model.Situacoes, new { @id = "situacao", @class = "form-control input-sm", @style = "width:100%;" })
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <label>Link</label>
                    <input id="link" class="form-control link-input lower-input" type="text" maxlength="4000" />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <label>Observação</label>
                    <textarea id="observacao" class="form-control" rows="10" maxlength="8000"></textarea>
                </div>
            </div>
        </div>

    </div>
</div>
<hr />
<div class="form-group">
    <div class="row">
        <div class="col-sm-12">
            <button id="btn-salvar" onclick="salvarclick()" type="button" class="btn btn-primary" aria-label="Left Align">Salvar <span class="fa fa-save fa-lg" aria-hidden="true"></span></button>
            <button id="btn-cancelar" onclick="cancelarclick()" type="button" class="btn btn-warning" aria-label="Left Align">Cancelar <span class="fa fa-times fa-lg" aria-hidden="true"></span></button>
        </div>
    </div>
</div>
<script src="~/js/Legislacao/New.js"></script>

<script>
    var urlIncluir = encodeURI('@Url.Action("Incluir", "Legislacao")');
</script>

Nomos/Views/Legislacao/Relacionados.cshtml
@model Nomos.Models.Legislacao.RelacionadosViewModel

@section styles{
    @*<link rel="Stylesheet" href="@Href("~/css/Legislacao/Index.css")" />*@
}

<div class="card mt-2">
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <h5 class="card-title">Legislações disponíveis</h5>
                    <hr />
                </div>
                <div class="col-md-2">
                </div>
                <div class="col-md-5">
                    <h5 class="card-title">Legislações relacionadas</h5>
                    <hr />
                </div>                
            </div>

            <div class="table-responsive">
                <div class="row">
                    @Html.Partial("~//Views/Legislacao/RelacionadosDisponiveis.cshtml", Model.LegislacaoDisponivel)

                    <div class="col-md-2 v-center" style="align-items:center">
                        <div style="height: 100%; border-left: .5px dashed;"></div>
                    </div>
                    

                    @Html.Partial("~//Views/Legislacao/RelacionadosSelecionados.cshtml", Model.LegislacaoRelacionada)
                </div>
            </div>


        </div>
    </div>
</div>


<script src="~/js/Legislacao/Relacionados.js"></script>