Nomos/Models/Empresa/EmpresaEditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nomos.Models.Empresa
{
    public class EmpresaEditViewModel
    {
        public int Id { get; set; }
        public string RazaoSocial { get; set; }
        public string NomeFantasia { get; set; }
        public string Cnpj { get; set; }
        public string EmailResponsavel { get; set; }
        public bool Cliente { get; set; }
        public bool Ativo { get; set; }

    }
}

Nomos/Models/Empresa/EmpresaFilterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nomos.Models.Empresa
{
    public class EmpresaFilterViewModel
    {
        public string Cnpj { get; set; }
        public string NomeFantasia { get; set; }
        public string RazaoSocial { get; set; }
    }
}

Nomos/Models/Empresa/EmpresaIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nomos.Models.Empresa
{
    public class EmpresaIndexViewModel
    {
        public EmpresaIndexViewModel()
        {
            ListaViewModel = new List<EmpresaListViewModel>();
            FilterViewModel = new EmpresaFilterViewModel();
        }

        public IList<EmpresaListViewModel> ListaViewModel { get; set; }

        public EmpresaFilterViewModel FilterViewModel { get; set; }
    }
}

Nomos/Models/Empresa/EmpresaListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nomos.Models.Empresa
{
    public class EmpresaListViewModel
    {
        public int Id { get; set; }
        public string Cnpj { get; set; }
        public string RazaoSocial { get; set; }
    }
}

Nomos/Models/Empresa/EmpresaNewViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Nomos.Models.Empresa
{
    public class EmpresaNewViewModel
    {
        public string RazaoSocial { get; set;}

        public string NomeFantasia { get; set; }

        public string Cnpj { get; set; }

        public string EmailResponsavel { get; set; }
    }
}

Nomos/Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Nomos.Business.Empresa;
using Nomos.Models.Empresa;

namespace Nomos.Controllers
{
    public class EmpresaController : BaseController
    {

        IEmpresaBusiness _empresaBusiness;
        private readonly IMapper _mapper;

        public EmpresaController(
            IEmpresaBusiness empresaBusiness,
            IMapper mapper,
            ICompositeViewEngine viewEngine) : base(viewEngine)
        {
            _empresaBusiness = empresaBusiness;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var lista = _empresaBusiness.Listar(true);

            var listaModel = _mapper.Map<IList<EmpresaListViewModel>>(lista);

            var model = new EmpresaIndexViewModel();
            model.ListaViewModel = listaModel;

            return View(model);
        }
        public IActionResult New()
        {
            var model = new EmpresaNewViewModel();

            return View(model);
        }

        public IActionResult Edit(int id)
        {
            var legislacao = _empresaBusiness.Buscar(id);
            var model = _mapper.Map<EmpresaEditViewModel>(legislacao);

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Filtrar([FromBody]EmpresaFilterViewModel model)
        {

            var filtro = _mapper.Map<Entities.Empresa>(model);

            var lista = _empresaBusiness.Filtrar(filtro);
            var listaModel = _mapper.Map<IList<EmpresaListViewModel>>(lista);

            var htmlRetorno = await RenderPartialViewToString("List", listaModel);

            return Json(htmlRetorno);
        }

        [HttpPost]
        public IActionResult Incluir([FromBody]EmpresaNewViewModel model)
        {
            Entities.Empresa entidade = null;

            try
            {

                if (_empresaBusiness.VerificarExisteCnpj(model.Cnpj))
                    return Json(new { Sucesso = false, Mensagem = "Cnpj já cadastrado para outra empresa" });
                else
                {
                    entidade = _mapper.Map<Entities.Empresa>(model);
                    entidade.Cliente = true;
                    entidade.Ativo = true;
                    _empresaBusiness.Incluir(entidade);
                }
            }
            catch (Exception ex)
            {
                return BadRequest(new { Mensagem = ex.Message });
            }

            return Json(new { Sucesso = true, entidade.Id });
        }


        [HttpPost]
        public IActionResult Atualizar([FromBody]EmpresaEditViewModel model)
        {
            try
            {
                var empresaExistente = _empresaBusiness.Buscar(model.Cnpj);

                if (empresaExistente.Id != model.Id)
                    return Json(new { Sucesso = false, Mensagem = "Cnpj já cadastrado para outra empresa" });
                else
                {
                    var entidade = _mapper.Map<Entities.Empresa>(model);
                    _empresaBusiness.Atualizar(entidade);
                }
            }
            catch (Exception ex)
            {
                return BadRequest(new { Mensagem = ex.Message });
            }

            return Json(new { Sucesso = true });
        }

        [HttpPost]
        public IActionResult Excluir([FromBody]EmpresaEditViewModel model)
        {
            try
            {
                _empresaBusiness.Excluir(model.Id);
            }
            catch (Exception ex)
            {
                return BadRequest(new { Mensagem = ex.Message });
            }

            return Json(new { Sucesso = true });
        }
    }
}

Nomos/Views/Empresa/Edit.cshtml
@model Nomos.Models.Empresa.EmpresaEditViewModel

@{
    ViewData["Title"] = "Empresa - Edição";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section styles{
    <link rel="Stylesheet" href="@Href("~/css/Empresa/Edit.css")" />
}

<h3>Empresa</h3>
<hr />
<div class="form-group">
    <div class="row">
        <div class="col-sm-12">
            <button id="btn-salvar" onclick="salvarClick()" type="button" class="btn btn-primary" aria-label="Left Align">Salvar <span class="fa fa-save fa-lg" aria-hidden="true"></span></button>
            <button id="btn-cancelar" onclick="cancelarClick()" type="button" class="btn btn-warning" aria-label="Left Align">Cancelar <span class="fa fa-times fa-lg" aria-hidden="true"></span></button>
            <button id="btn-excluir" onclick="excluirClick()" type="button" class="btn btn-danger" aria-label="Left Align">Excluir <span class="fa fa-trash fa-lg" aria-hidden="true"></span></button>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="form-group">

            <div class="row">
                <input id="id" type="hidden" value="@Model.Id" />
                <input id="cliente" type="hidden" value="@Model.Cliente.ToString()"/>
                <input id="ativo" type="hidden" value="@Model.Ativo.ToString()" />

                <div class="col-sm-3">
                    <label>Cnpj</label>
                    <input id="cnpj" class="form-control" type="text" maxlength="14" onkeypress="return isNumber(event)" value="@Model.Cnpj" />
                </div>

                <div class="col-sm-5">
                    <label>Razao Social</label>
                    <input id="razao-social" class="form-control" type="text" maxlength="500" value="@Model.RazaoSocial" />
                </div>
                <div class="col-sm-4">
                    <label>Nome Fantasia</label>
                    <input id="nome-fantasia" class="form-control" type="text" maxlength="200" value="@Model.NomeFantasia" />
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <label>E-mail responsável</label>
                    <input id="email-responsavel" class="form-control lower-input" type="text" maxlength="500"  value="@Model.EmailResponsavel"/>
                </div>
            </div>
        </div>

    </div>
</div>
<hr />
<div class="form-group">
    <div class="row">
        <div class="col-sm-12">
            <button id="btn-salvar" onclick="salvarClick()" type="button" class="btn btn-primary" aria-label="Left Align">Salvar <span class="fa fa-save fa-lg" aria-hidden="true"></span></button>
            <button id="btn-cancelar" onclick="cancelarClick()" type="button" class="btn btn-warning" aria-label="Left Align">Cancelar <span class="fa fa-times fa-lg" aria-hidden="true"></span></button>
            <button id="btn-excluir" onclick="excluirClick()" type="button" class="btn btn-danger" aria-label="Left Align">Excluir <span class="fa fa-trash fa-lg" aria-hidden="true"></span></button>
        </div>
    </div>
</div>
<script src="~/js/Empresa/Edit.js"></script>

<script>
    var urlAtualizar = encodeURI('@Url.Action("Atualizar", "Empresa")');
    var urlExcluir = encodeURI('@Url.Action("Excluir", "Empresa")');
</script>

Nomos/Views/Empresa/Filter.cshtml
@model Nomos.Models.Empresa.EmpresaFilterViewModel

<div class="card">
    <div class="card-body">
        <div class="form-group">

            <div class="row mt-2">
                <div class="col-sm-2">
                    <label>Cnpj</label>
                    <input id="cnpj" class="form-control" type="text" maxlength="14" />
                </div>

                <div class="col-sm-4">
                    <label>Nome Fantasia</label>
                    <input id="nome-fantasia" class="form-control" type="text" maxlength="200" />
                </div>

                <div class="col-sm-4">
                    <label>Razão Social</label>
                    <input id="razao-social" class="form-control" type="text" maxlength="500" />
                </div>

                <div class="col-sm-2 text-right">
                    <br>
                    <button id="btn-filtrar" onclick="filtrarClick()" type="button" class="btn btn-primary" aria-label="Left Align">Filtrar <span class="fa fa-search fa-lg" aria-hidden="true"></span></button>
                </div>

            </div>
        </div>
    </div>
</div>
<hr />

<script src="~/js/Empresa/Filter.js"></script>


<script>
    var urlFiltrar = encodeURI('@Url.Action("Filtrar", "Empresa")');
</script>

Nomos/Views/Empresa/Index.cshtml
@model Nomos.Models.Empresa.EmpresaIndexViewModel

@{
    ViewData["Title"] = "Empresa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles{
    @*<link rel="Stylesheet" href="@Href("~/css/Empresa/Index.css")" />*@
}

<div class="form-group">
    <div class="row">
        <div class="col-sm-2">
            <h3>Empresa</h3>
        </div>
        <div class="col-sm-10 text-right">
            <button id="btn-incluir" onclick="incluirClick()" type="button" class="btn btn-success" aria-label="Left Align"><span class="fa fa-file fa-lg" aria-hidden="true"></span></button>
        </div>
    </div>
</div>
<hr />

@Html.Partial("~//Views/Empresa/Filter.cshtml", Model.FilterViewModel)
<div id="resultado">
    @Html.Partial("~//Views/Empresa/List.cshtml", Model.ListaViewModel)
</div>

<script src="~/js/Empresa/Index.js"></script>

Nomos/Views/Empresa/List.cshtml
@model List<Nomos.Models.Empresa.EmpresaListViewModel>


<div class="box">
    <div class="box-content">
        @if (Model.Count > 0)
        {
        <table id="gridEmpresa" class="table table-bordered table-striped">

            <thead>
                <tr>
                    <th hidden>Id</th>
                    <th>Cnpj</th>
                    <th>Razao Social</th>
                    <th></th>
                    <th></th>
                </tr>
            <thead>
            <tbody>
                @foreach (var item in Model)
                    {
                <tr id="rowId_@item.Id">
                    <td hidden>@item.Id"</td>
                    <td>@item.Cnpj</td>
                    <td>@item.RazaoSocial</td>
                    <td style="text-align:center"><i class="fa fa-fw fa-edit" style="cursor:pointer" onclick="editarClick(@item.Id)"></i></td>
                    <td style="text-align:center"><i class="fa fa-fw fa-trash" style="cursor:pointer" onclick="excluirClick(@item.Id)"></i></td>
                </tr>
                    }
            </tbody>
        </table>
        }
        else
        {
        <table>
            <thead>
                <tr>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td style="color:red">Nenhum registro encontrado</td>
                </tr>
            </tbody>
        </table>
        }

    </div>
    <!--end: BOX CONTENT-->
</div>
<!--end: BOX-->

<script src="~/js/Empresa/List.js"></script>


<script>
    var urlExcluir = encodeURI('@Url.Action("Excluir", "Empresa")');
</script>

Nomos/Views/Empresa/New.cshtml
@model Nomos.Models.Empresa.EmpresaNewViewModel

@{
    ViewData["Title"] = "Empresa - Inclusão";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section styles{
    <link rel="Stylesheet" href="@Href("~/css/Empresa/New.css")" />
}

<h3>Empresa</h3>
<hr />
<div class="form-group">
    <div class="row">
        <div class="col-sm-12">
            <button id="btn-salvar" onclick="salvarclick()" type="button" class="btn btn-primary" aria-label="Left Align">Salvar <span class="fa fa-save fa-lg" aria-hidden="true"></span></button>
            <button id="btn-cancelar" onclick="cancelarclick()" type="button" class="btn btn-warning" aria-label="Left Align">Cancelar <span class="fa fa-times fa-lg" aria-hidden="true"></span></button>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="form-group">

            <div class="row">
                <div class="col-sm-3">
                    <label>Cnpj</label>
                    <input id="cnpj" class="form-control" type="text" maxlength="14" onkeypress="return isNumber(event)" />
                </div>

                <div class="col-sm-5">
                    <label>Razao Social</label>
                    <input id="razao-social" class="form-control" type="text" maxlength="500" />
                </div>
                <div class="col-sm-4">
                    <label>Nome Fantasia</label>
                    <input id="nome-fantasia" class="form-control" type="text" maxlength="200" />
                </div>                
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <label>E-mail responsável</label>
                    <input id="email-responsavel" class="form-control lower-input" type="text" maxlength="500" />
                </div>
            </div>

        </div>

    </div>
</div>
<hr />
<div class="form-group">
    <div class="row">
        <div class="col-sm-12">
            <button id="btn-salvar" onclick="salvarclick()" type="button" class="btn btn-primary" aria-label="Left Align">Salvar <span class="fa fa-save fa-lg" aria-hidden="true"></span></button>
            <button id="btn-cancelar" onclick="cancelarclick()" type="button" class="btn btn-warning" aria-label="Left Align">Cancelar <span class="fa fa-times fa-lg" aria-hidden="true"></span></button>
        </div>
    </div>
</div>
<script src="~/js/Empresa/New.js"></script>

<script>
    var urlIncluir = encodeURI('@Url.Action("Incluir", "Empresa")');
</script>