Nomos/Models/Menu/MenuViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nomos.Models.Menu
{
    public class MenuViewModel
    {

        public MenuViewModel()
        {
            this.Empresas = new SelectList(new List<ItemDropModel>());
        }

        public int EmpresaId { get; set; }
        public string NomeEmpresa { get; set; }
        public SelectList Empresas { get; set; }
        public string NomeUsuario { get; set; }
        public bool IsAdmin { get; set; }
    }
}

Nomos/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Nomos.Business.Usuario;
using Nomos.Business.Empresa;
using Nomos.Models.Login;
using Nomos.Util;
using System.Text.RegularExpressions;

namespace Nomos.Controllers
{
    public class LoginController : BaseController
    {

        IUsuarioBusiness _usuarioBusiness;
        IEmpresaBusiness _empresaBusiness;

      

        public LoginController(IUsuarioBusiness usuarioBusiness, IEmpresaBusiness empresaBusiness, ICompositeViewEngine viewEngine) : base(viewEngine)
        {
            _usuarioBusiness = usuarioBusiness;
            _empresaBusiness = empresaBusiness;
        }


        public IActionResult Index(LoginIndexViewModel model)
        {

            if (model != null && model.CnpjEmpresa == null)
            {
                return View();
            }

            var validacaoLogin = ValidarLogin(model);
            if(validacaoLogin.Validado)
            {
                //Create the identity for the user  
                var identity = new ClaimsIdentity(new[] {
                        new Claim(ClaimTypes.Name, model.NomeUsuario)
                    }, CookieAuthenticationDefaults.AuthenticationScheme);

                var principal = new ClaimsPrincipal(identity);

                var login = HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                this.UsuarioLogado = validacaoLogin.Usuario;
                this.EmpresaSelecionada = validacaoLogin.Usuario.Empresa;

                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("Validacao", validacaoLogin.Mensagem);
            }

            return View();
        }



        public JsonResult EfetuarLogoff()
        {
            try
            {
                var login = HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            }
            catch (Exception ex)
            {
                return Json(new { Sucesso = false, Mensagem = "Erro ao efetuar logoff " + ex.Message});
            }

            return Json(new { Sucesso = true});
        }


        public ValidacaoLoginModel ValidarLogin(LoginIndexViewModel model)
        {
            var usuario = _usuarioBusiness.FiltrarLogin(model.NomeUsuario);

            //Usuário inexistente
            if (usuario == null)
                return new ValidacaoLoginModel { Validado = false, Usuario = null, Mensagem = "CNPJ, usuário ou senha inválidos" };


            var cnpjEmpresa = model.CnpjEmpresa.Replace(".", "").Replace("-", "").Replace("/","");
            var empresa = _empresaBusiness.Buscar(cnpjEmpresa);
            //Empresa inexistente
            if (empresa == null)
                return new ValidacaoLoginModel { Validado = false, Usuario = null, Mensagem = "CNPJ, usuário ou senha inválidos" };


            //Empresa diferente
            if (empresa.Id != usuario.EmpresaId)
                return new ValidacaoLoginModel { Validado = false, Usuario = null, Mensagem = "CNPJ, usuário ou senha inválidos" };

            //Usuário inativo
            if (usuario.SituacaoId != 1)
                return new ValidacaoLoginModel { Validado = false, Usuario = null, Mensagem = "Usuário inativo" };

            var senhaHash = SHA.GenerateSHA256String(model.Senha);

            //Senha não confere
            if (usuario.Senha != senhaHash)
                return new ValidacaoLoginModel { Validado = false, Usuario = null, Mensagem = "CNPJ, usuário ou senha inválidos" };

            return new ValidacaoLoginModel { Validado = true, Usuario = usuario, Mensagem = string.Empty };
        }


    }
}

Nomos/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Nomos.Business.Empresa;
using Nomos.Models;
using Nomos.Models.Menu;

namespace Nomos.Controllers
{
    public class MenuController : BaseController
    {
        IEmpresaBusiness _empresaBusiness;

       public MenuController(IEmpresaBusiness empresaBusiness, ICompositeViewEngine viewEngine) : base(viewEngine)
        {
           
            _empresaBusiness = empresaBusiness;
        }

       
        public JsonResult AlterarEmpresaSelecionada([FromBody]MenuViewModel model)
        {
            var empresa = _empresaBusiness.Buscar(model.EmpresaId);

            if(empresa == null)
            {
                return Json(new { Sucesso = false, Mensagem = "Empresa não localizada" });
            }

            this.EmpresaSelecionada = null;
            this.EmpresaSelecionada = empresa;
            return Json(new { Sucesso = true });

        }
       


    }

}

Nomos/Views/Shared/Components/Menu/MenuViewComponent.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nomos.Business.Empresa;
using Nomos.Entities;
using Nomos.Models;
using Nomos.Models.Menu;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nomos.Views.Shared.Components
{
    public class MenuViewComponent : ViewComponent
    {

        private readonly IEmpresaBusiness _empresaBusiness;
        private readonly IHttpContextAccessor _contextAccessor;

        public MenuViewComponent(IEmpresaBusiness empresaBusiness, IHttpContextAccessor contextAccessor)
        {
            _empresaBusiness = empresaBusiness;
            _contextAccessor = contextAccessor;

        }
        public IViewComponentResult Invoke()
        {

            var usuario = _contextAccessor.HttpContext.Session.GetObjectFromJson<Usuario>("usuarioLogado");
            var empresa = _contextAccessor.HttpContext.Session.GetObjectFromJson<Empresa>("empresaSelecionada");
            var model = new MenuViewModel();

            if (usuario != null)
            {
                model.Empresas = RetornarEmpresas();
                model.EmpresaId = empresa.Id;
                model.NomeEmpresa = usuario.Empresa.NomeFantasia;
                model.NomeUsuario = usuario.Login;
                model.IsAdmin = usuario.PerfilAcessoId == 1;//admin

            }
            else
            {
                HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
                HttpContext.Response.Redirect("login");
            }


            return View(model);
        }


        private SelectList RetornarEmpresas()
        {
            var empresas = _empresaBusiness.Listar();

            List<ItemDropModel> itens = new List<ItemDropModel>();

            foreach (var empresa in empresas)
            {
                itens.Add(new ItemDropModel { Id = empresa.Id, Nome = empresa.NomeFantasia });
            }

            return new SelectList(itens, "Id", "Nome");
        }


    }
}

Nomos/Views/Shared/Components/Menu/Default.cshtml
@model Nomos.Models.Menu.MenuViewModel

<nav class="navbar navbar-expand-lg navbar-dark bg-custom" style="background-color:darkgreen">
    <a class="navbar-brand" href="#"><img src="~/images/Logo64.png" /></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
        </ul>
        <form class="form">
            <div class="row">
                <div class="col-xs-2 mr-2">

                    @*@if (Model.IsAdmin)
                    {
                        @Html.DropDownListFor(model => model.EmpresaId, Model.Empresas, new { @id = "empresa", @class = "form-control input-sm", @style = "width:100%;" })
                    }*@
                </div>
                <div class="col-xs-2 mr-2">
                    <button id="btn-logoff" onclick="logoffClick()" type="button" class="btn btn-outline-success" aria-label="Left Align">@Model.NomeUsuario <span class="fa fa-sign-out-alt fa-lg" aria-hidden="true"></span></button>
                </div>
            </div>
        </form>
    </div>
</nav>

<script src="~/js/Menu/Default.js"></script>

<script>
    var urlLogoff = encodeURI('@Url.Action("EfetuarLogoff", "Login")');
    var urlAlterarEmpresa = encodeURI('@Url.Action("AlterarEmpresaSelecionada", "Menu")');
</script>